### PR TITLE
Pull in Clownacy's changes

### PR DESCRIPTION
**Pull request by flamewing**
Leaving this as a reminder to myself.

### CODE REVIEW

**Comment by flamewing** [comment]
Also relevant: https://github.com/Clownacy/Sonic-2-Clone-Driver-v2/blob/master/engine/_smps2asm_inc.asm

**Comment by Clownacy** [comment]
Oh right, those. Technically, I'm not finished with those changes yet. I've been meaning to do some more testing, make sure S3/S&K/S3D are bit-perfect, and add SCD SFX support ([this might be relevant](https://github.com/Clownacy/New-Sonic-CD-SFX-driver/blob/master/_smps2asm_inc.asm)).

**Comment by flamewing** [comment]
I think that the pull request will keep updating itself automatically as you commit code to your repository. I have no rush to merge, it is, as I mentioned, a reminder to myself.

If memory serves, I had made sure that S&K stuff was bit perfect, even extracting data by hand to ensure it was. I *think* I did the same for S3 and S3D, but I am less certain.

**Comment by flamewing** [comment]
Regarding your SCD driver, I think [this](https://pastebin.com/6ajqXf7Y) may be of use. It is the constants I defined for the subcpu commands (including PCM commands), and SFX IDs. Also includes (by accident) the PLC constants.

I named many of them based on S2 or S1 (IIRC).

**Comment by Clownacy** [comment]
Awesome, thanks.

**Comment by flamewing** [comment]
Out of curiosity, are there any more commits planned?

**Comment by Clownacy** [comment]
Yeah, I've been meaning to check that the S3 files are bit-perfect, and backport my SCD SFX/Chaotix support with some improvements.

Speaking of, I'm not exactly sure what to do about some of the S3 files: S3 has a few unique songs, but others are just bugged S&K songs. So should I bother adding fixed versions of those to the `music-optimized` directory?

I suppose it would be fine to merge the current commits until I get around to making the rest of them.

**Comment by flamewing** [comment]
For the S3 songs, maybe just having a text file in the music-optimized directory saying that all "missing" songs in the directory should be taken from S&K instead?

Again, no rush; I was just wondering, given the near month delay. And I am interested in the SCD/Chaotix stuff as well.

**Pull request merged**
